### ISSUE TITLE
echo -en in update_image.pl doesn't work in dash.

### ISSUE THREAD

**Issue by williamspatrick** [open-power/pnor#30]
If you run 'echo -en VERSION' in dash you get '-en VERSION'.  We need to find a workaround for Ubuntu builders.

**Comment by williamspatrick** [comment]
I suspect that running 'env echo -en VERSION\\0' instead of 'echo -en VERSION\\0' will resolve this.  The dash builtin for 'echo' doesn't seem to support -e.

**Comment by scprek** [comment]
Just tested 'env echo -en VERSION\0' in dash and bash, seems to work.

**Comment by scprek** [comment]
https://github.com/open-power/pnor/pull/31

**Comment by scprek** [comment]
Resolved with

open-power/openpower-pnor@a9777445212ffef1098383f67ff59acb1c6167a9
