### ISSUE TITLE
NVRAM partition falsely claims to use ECC

### ISSUE THREAD

**Issue by sammj** [open-power/pnor#46]
Listing available partitions with pflash displays the NVRAM partition as being ECC-corrected:

> ID=18           NVRAM 01de2000..01e72000 (actual=00090000) [ECC]

But when dumping the partition itself this appears to not be the case, for example:

```
00000ff0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00001000: 700c 1000 636f 6d6d 6f6e 0000 0000 0000  p...common......
00001010: 7065 7469 7462 6f6f 742c 626f 6f74 6465  petitboot,bootde
00001020: 7673 3d6e 6574 776f 726b 2064 6973 6b20  vs=network disk 
00001030: 616e 7920 0070 6574 6974 626f 6f74 2c77  any .petitboot,w
00001040: 7269 7465 3f3d 6661 6c73 6500 7065 7469  rite?=false.peti
00001050: 7462 6f6f 742c 7469 6d65 6f75 743d 3330  tboot,timeout=30
00001060: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00001070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00001080: 0000 0000 0000 0000 0000 0000 0000 0000  ................
```

AFAIK powerpc-utils (ie. the nvram utility) isn't ECC-aware, so perhaps it is easier to remove the ECC marker for the NVRAM partition.

**Comment by williamspatrick** [comment]
@sammj : How about a pull request?  There are a few XML files that you'll just need to remove the ECC line on.  Should be pretty straight forward.

**Comment by sammj** [comment]
Voila! https://github.com/open-power/pnor/pull/47
Built and boot-tested, I believe I caught all mentions of ECC for NVRAM.
