### ISSUE TITLE
ATTR_TEMP and HBBL overlap

### ISSUE THREAD

**Issue by stewart-ibm** [open-power/pnor#90]
https://github.com/open-power/pnor/blob/1927047ef694803ec2d5252775ae88285f2f9a2d/p9Layouts/defaultPnorLayout_64.xml#L280
https://github.com/open-power/pnor/blob/1927047ef694803ec2d5252775ae88285f2f9a2d/p9Layouts/defaultPnorLayout_64.xml#L268

HBBL and ATTR_TEMP have the same physical offset.

This causes weird `op-build` build failures along the lines of "eyeCatch cannot be empty" which is due to the buildpnor.pl scripts not particularly gracefully handling overlapping partitions.

**Comment by dcrowell77** [comment]
Fixed with https://github.com/open-power/pnor/pull/91

**Comment by stewart-ibm** [comment]
FIxed in https://github.com/open-power/pnor/pull/91
